.PHONY: clean All

All:
	@echo "----------Building project:[ ChordProc - Debug ]----------"
	@cd "ChordProc" && "$(MAKE)" -f  "ChordProc.mk"
clean:
	@echo "----------Cleaning project:[ ChordProc - Debug ]----------"
	@cd "ChordProc" && "$(MAKE)" -f  "ChordProc.mk" clean
