.PHONY: clean All

All:
	@echo "----------Building project:[ ChordProcessing - Debug ]----------"
	@cd "ChordProcessing" && "$(MAKE)" -f  "ChordProcessing.mk"
clean:
	@echo "----------Cleaning project:[ ChordProcessing - Debug ]----------"
	@cd "ChordProcessing" && "$(MAKE)" -f  "ChordProcessing.mk" clean
